set(QLOCKY_APP_VERSION_MAJOR "0")
set(QLOCKY_APP_VERSION_MINOR "0")
set(QLOCKY_APP_VERSION_PATCH "1")

set(QLOCKY_APP_VERSION "${QLOCKY_APP_VERSION_MAJOR}.${QLOCKY_APP_VERSION_MINOR}.${QLOCKY_APP_VERSION_PATCH}")

message(STATUS "QLOCKY_APP_VERSION ${QLOCKY_APP_VERSION}")
