if (PLATFORM_DETECTED)
    return()
endif()

set(OS_IS_LINUX OFF)
set(OS_IS_QLOCKY OFF)

set(_platform_hint "")
if (DEFINED CMAKE_TARGET_SDK AND NOT "${CMAKE_TARGET_SDK}" STREQUAL "")
    set(_platform_hint "${CMAKE_TARGET_SDK}")
elseif (DEFINED CMAKE_SYSTEM_NAME AND NOT "${CMAKE_SYSTEM_NAME}" STREQUAL "")
    set(_platform_hint "${CMAKE_SYSTEM_NAME}")
elseif (DEFINED CMAKE_HOST_SYSTEM_NAME AND NOT "${CMAKE_HOST_SYSTEM_NAME}" STREQUAL "")
    set(_platform_hint "${CMAKE_HOST_SYSTEM_NAME}")
endif()

if ("${_platform_hint}" MATCHES "Linux")
    set(OS_IS_LINUX ON)
elseif ("${_platform_hint}" MATCHES "Qlocky")
    set(OS_IS_QLOCKY ON)
else()
    message(FATAL_ERROR "Unsupported platform: ${_platform_hint}")
endif()

set(PLATFORM_DETECTED ON)
